## Everything in this file gets sourced during `simInit()`,
## and all functions and objects are put into the `simList`.
## To use objects, use `sim$xxx` (they are globally available to all modules).
## Functions can be used without `sim$` as they are namespaced to the module,
## just like functions in R packages.
## If exact location is required, functions will be: `sim$<moduleName>$FunctionName`.
defineModule(sim, list(
  name = "assistedMigrationBC",
  description = "",
  keywords = "",
  authors = structure(list(list(given = c("Ian"), family = "Eddy", role = c("aut", "cre"), email = "ian.eddy@canada.com", comment = NULL)), class = "person"),
  childModules = character(0),
  version = list(SpaDES.core = "1.0.0.9000", assistedMigrationBC = "0.0.0.9000"),
  timeframe = as.POSIXlt(c(NA, NA)),
  timeunit = "year",
  citation = list("citation.bib"),
  documentation = deparse(list("README.txt", "assistedMigrationBC.Rmd")),
  reqdPkgs = list('data.table', 'magrittr', 'raster'),
  parameters = rbind(
    #defineParameter("paramName", "paramClass", value, min, max, "parameter description"),
    defineParameter(".plotInitialTime", "numeric", NA, NA, NA,
                    "Describes the simulation time at which the first plot event should occur."),
    defineParameter(".plotInterval", "numeric", NA, NA, NA,
                    "Describes the simulation time interval between plot events."),
    defineParameter(".saveInitialTime", "numeric", NA, NA, NA,
                    "Describes the simulation time at which the first save event should occur."),
    defineParameter(".saveInterval", "numeric", NA, NA, NA,
                    "This describes the simulation time interval between save events."),
    defineParameter(".useCache", "logical", FALSE, NA, NA,
                    paste("Should this entire module be run with caching activated?",
                          "This is generally intended for data-type modules, where stochasticity",
                          "and time are not relevant")),
    defineParameter("sppEquivCol", "character", "Boreal", NA, NA,
                    "The column in sim$specieEquivalency data.table to use as a naming convention")
  ),
  inputObjects = bind_rows(
    #expectsInput("objectName", "objectClass", "input object description", sourceURL, ...),
    expectsInput("BECkey", 'data.table', desc = "key that contains the raster ID and corresponding zone/subzone/var of projected BECs",
                 sourceURL = "https://drive.google.com/open?id=1v4_ZSXFAopYrTPpapxB3cHAIJJLE0sX0"),
    expectsInput("cohortData", "data.table",
                 desc = "Columns: B, pixelGroup, speciesCode, Indicating several features about ages and current vegetation of stand"),
    expectsInput("currentBEC", 'RasterLayer', desc = "the projected BEC zones at time(sim)"),
    expectsInput("sppEquiv", "data.table",
                 desc = "table of species equivalencies. See LandR::sppEquivalencies_CA.",
                 sourceURL = ""),
    expectsInput("transferTable", 'data.table',
                 desc = "table of transfer functions representing climate-sensitive genetic growth - from Greg O'Neil",
                 sourceURL = 'https://drive.google.com/open?id=1N0VrvdgtzQLzlVhMYAg-xKPVLcxOZTSe'),
    expectsInput("projectedBEC", "rasterStack",
                 desc = "the projected BEC zones; already reclassified to ensure consistent raster representation",
                 sourceURL = 'https://drive.google.com/open?id=1SJf9zQqBcznw5uByfRZ5ulk2ktfHia26'),
    expectsInput('ecoregionMap', "rasterLayer",
                 desc = paste("a map of ecoregions with corresponding RAT that contains the BEC code of each ecoregion.",
                               'This must be generated by running Biomass_borealDataPrep with the projectedBEC$BECref as ecoregion')),
    expectsInput(objectName = 'sppEquiv', objectClass = 'data.table', desc = 'sppEquivalencies table. See LandR::sppEquivalencies_CA')
  ),
  outputObjects = bind_rows(
    #createsOutput("objectName", "objectClass", "output object description", ...),
    createsOutput(objectName = 'provenanceTable', objectClass = 'data.table',
                  desc = 'a table that dictates what species are planted at what locations. Has columns ecoregionGroup, species, provenance')
  )
))

## event types
#   - type `init` is required for initialization

doEvent.assistedMigrationBC = function(sim, eventTime, eventType) {
  switch(
    eventType,
    init = {
      ### check for more detailed object dependencies:
      ### (use `checkObject` or similar)

      # do stuff for this event
      sim <- Init(sim)

      # schedule future event(s)
      sim <- scheduleEvent(sim, P(sim)$.plotInitialTime, "assistedMigrationBC", "plot")
      sim <- scheduleEvent(sim, P(sim)$.saveInitialTime, "assistedMigrationBC", "save")
      sim <- scheduleEvent(sim, 2020, 'assistedMigrationBC', 'updateProvenanceTable')

    },
    plot = {

    },
    save = {

    },
    updateProvenanceTable = {
      # ! ----- EDIT BELOW ----- ! #
      sim$currentBEC <- sim$projectedBEC[[grep(pattern = paste0('*', time(sim)), value = TRUE, x = names(sim$projectedBEC))]]

      sim$provenanceTable <- generateBCProvenanceTable(transferTable = sim$transferTable,
                                                       BECkey = sim$BECkey,
                                                       projectedBEC = sim$currentBEC,
                                                       ecoregionMap = sim$ecoregionMap,
                                                       sppEquiv = sim$sppEquiv,
                                                       sppEquivCol = P(sim)$sppEquivCol)
      if (time(sim) < 2080) {
        #The bECs update every 30 years REF - 2020, 2050, 2080
        sim  <- scheduleEvent(sim, time(sim) + 30, "assistedMigrationBC", 'updateProvenanceTable')
      }

    },
    warning(paste("Undefined event type: \'", current(sim)[1, "eventType", with = FALSE],
                  "\' in module \'", current(sim)[1, "moduleName", with = FALSE], "\'", sep = ""))
  )
  return(invisible(sim))
}

## event functions
#   - keep event functions short and clean, modularize by calling subroutines from section below.

### template initialization
Init <- function(sim) {

  sim$provenanceTable <- generateBCProvenanceTable(transferTable = sim$transferTable,
                                                   BECkey = sim$BECkey,
                                                   projectedBEC = sim$projectedBEC$BECref,
                                                   ecoregionMap = sim$ecoregionMap,
                                                   sppEquiv = sim$sppEquiv,
                                                   sppEquivCol = P(sim)$sppEquivCol)
  if (time(sim) < 2020) {
    sim$currentBEC <- sim$projectedBEC$BECref
  } else {
    warning("the assisted migration module should start before 2020")
    sim$currentBEC <- sim$projectedBEC$BEC2020
  }

  return(invisible(sim))
}

### template for save events
Save <- function(sim) {
  # ! ----- EDIT BELOW ----- ! #
  # do stuff for this event
  sim <- saveFiles(sim)

  # ! ----- STOP EDITING ----- ! #
  return(invisible(sim))
}

### template for plot events
plotFun <- function(sim) {
  # ! ----- EDIT BELOW ----- ! #
  # do stuff for this event
  #Plot(sim$object)

  # ! ----- STOP EDITING ----- ! #
  return(invisible(sim))
}

.inputObjects <- function(sim) {

  cacheTags <- c(currentModule(sim), "function:.inputObjects") ## uncomment this if Cache is being used
  dPath <- asPath(getOption("reproducible.destinationPath", dataPath(sim)), 1)
  message(currentModule(sim), ": using dataPath '", dPath, "'.")

  # ! ----- EDIT BELOW ----- ! #
  if (!suppliedElsewhere("BECkey", sim)) {
    sim$BECkey <- prepInputs(url = extractURL('BECkey', sim),
                             destinationPath = dPath,
                             fun = 'data.table::fread', useCache = TRUE,
                             overwrite = TRUE,
                             userTags = c(cacheTags, 'BECkey'))
  }


  if (!suppliedElsewhere("transferTable", sim)) {
    sim$transferTable <- prepInputs(url = extractURL('transferTable', sim), destinationPath = dPath,
                                    targetFile = "GregONeilData_Formatted.csv", fun = 'fread')
  }

  # if (!suppliedElsehwere("cohortData", sim)) {
  #   stop("This module needs cohortData. Please run one of Biomass_core or Biomass_borealDataPrep or contact authors")
  # }

  if (!suppliedElsewhere("projectedBEC", sim)) {

    sim$projectedBEC <- prepInputs(targetFile = 'reclassifiedBECs.grd',
                                   url = extractURL("projectedBEC", sim),
                                   destinationPath = dPath,
                                   fun = "raster::stack",
                                   alsoExtract = 'reclassifiedBECs.gri',
                                   studyArea = sim$studyArea,
                                   rasterToMatch = sim$rasterToMatch,
                                   purge = 7,
                                   useCache = TRUE,
                                   overwrite = TRUE,
                                   userTags = c(cacheTags, 'flyingBECs')) #assume we only need these for studyArea!
  }
  # ! ----- STOP EDITING ----- ! #
  return(invisible(sim))
}

### add additional events as needed by copy/pasting from above
